#ifndef
#define
#include
#endif

#ifndef
#include ".h"
#endif

#ifndef
#include ".hpp"
#endif

#ifndef
#define
#include <.h>
#endif

//*****************************  <xxxxx.h>

#ifndef  STDIOH
#define  STDIOH
#include <stdio.h>
#endif

#ifndef  GRAPHICSH
#define  GRAPHICSH
#include <graphics.h>
#endif

#ifndef  CONIOH
#define  CONIOH
#include <conio.h>
#endif

#ifndef  PROCESSH
#define  PROCESSH
#include <process.h>
#endif

#ifndef  STDLIBH
#define  STDLIBH
#include <stdlib.h>
#endif

#ifndef  STRINGH
#define  STRINGH
#include <string.h>
#endif

#ifndef  MEMH
#define  MEMH
#include <mem.h>
#endif

#ifndef BIOSH
#define BIOSH
#include <bios.h>
#endif

#ifndef DOSH
#define DOSH
#include <dos.h>
#endif

#ifndef DIRH
#define DIRH
#include <dir.h>
#endif


#ifndef  IOH
#define  IOH
#include <io.h>
#endif

#ifndef  SETJMP
#define  SETJMP
#include <setjmp.h>
#endif

#ifndef  ALLOCH
#define  ALLOCH
#include <alloc.h>
#endif

#ifndef  MATHH
#define  MATHH
#include <math.h>
#endif


//////********************   "xxxxx.hpp"

#ifndef APLICATIONOFPROGRAMM
#include "APPLIC.hpp"
#endif

#ifndef   BASE
#include "base.hpp"
#endif

#ifndef  BASEMATH
#include "basemath.hpp"
#endif

#ifndef  BORDER
#include "border.hpp"
#endif

#ifndef  BOX
#include "box.hpp"
#endif

#ifndef  BOXI
#include "boxi.hpp"
#endif

#ifndef  BUTTON
#include "button.hpp"
#endif

#ifndef  CLAST
#include "clast.hpp"
#endif

#ifndef  CONTROL
#include "control.hpp"
#endif

#ifndef  CURDIR
#include "curdir.hpp"
#endif

#ifndef  DIAGNOST
#include "diagnost.hpp"
#endif

#ifndef  ERROR
#include "error.hpp"
#endif

#ifndef   EVENT
#include "event.hpp"
#endif

#ifndef  FCENTRE
#include "fcentre.hpp"
#endif

#ifndef   FSTATION
#include "fstation.hpp"
#endif

#ifndef  FUNCTION
#include "function.hpp"
#endif

#ifndef GROUP
#include "group.hpp"
#endif

#ifndef  GSIMPLE
#include "gsimple.hpp"
#endif

#ifndef HANDLEPOINT
#include "hstation.hpp"
#endif

#ifndef  KEYBOARD
#include "keyboard.hpp"
#endif

#ifndef KURSOR
#include "kursor.hpp"
#endif

#ifndef  LINE
#include "line.hpp"
#endif

#ifndef LINEINPUT
#include "lineinpu.hpp"
#endif

#include "linebar.hpp"
#endif


#ifndef LINEBAR
#include "linebar.hpp"
#endif

#ifndef MODALS
#include "modals.hpp"
#endif

#ifndef MOUSE
#include "mouse.hpp"
#endif

#ifndef OBJECT
#include "object.hpp"
#endif

#ifndef  OXY
#include "oxy.hpp"
#endif

#ifndef  PIXEL
#include "pixel.hpp"
#endif

#ifndef  PROTO
#include "proto.hpp"
#endif

#ifndef   RAMKA
#include "ramka.hpp"
#endif

#ifndef  SIMPLE
#include "simple.hpp"
#endif

#ifndef  SOURSE
#include "sourse.hpp"
#endif

#ifndef   TEXTBAR
#include "textbar.hpp"
#endif

#ifndef  VIEW
#include "view.hpp"
#endif

#ifndef  WINDOW
#include "window.hpp"
#endif

//********************  "XXXX.H"

#ifndef  ARM
#include "ARM.h"
#endif

#ifndef  BOARD
#include "board.h"
#endif

#ifndef  METOD
#include "metod.h"
#endif

#ifndef  PCXLIBH
#define  PCXLIBH
#include "pcxlib.h"
#endif

#ifndef POISK
#include "poisk.h"
#endif

#ifndef SLAVE
#include "slave.h"
#endif

#ifndef  TKEYS
#include "tkeys.h"
#endif

#ifndef  XMS
#include "xms.h"
#endif


#pragma hdrstop
