del libnet.lib
tlib libnet.lib /c + applic.obj + basemath.obj + border.obj +box.obj + buildm.obj
tlib libnet.lib /c + button.obj + dbf.obj + desktop.obj + diagnost.obj + error.obj
tlib libnet.lib /c + event.obj + fcentre.obj + fstation.obj + function.obj + group.obj 
tlib libnet.lib /c + gsimple.obj + help.obj + hstation.obj + line.obj + linebar.obj
tlib libnet.lib /c + lineinput.obj + newtest.obj + object.obj + options.obj + proto.obj
tlib libnet.lib /c + simple.obj + sourse.obj +textbar.obj + view.obj + window.obj + pcx_cl.lib 
tlib libnet.lib /c + netobj.lib