#ifndef TETRISH
#define TETRISH
enum{ // Константы идентификаторы типа фигуры
	figNo,		// nofigure

	figOne,        // █
	figUpper,
	figBlok,


	figTwo,        // ██
	figThree,      //
	figFour,

	figUpTwo,
	figUpThree,
	figUpFour,


	figZ,
	figMZ,
	figUpZ,
	figUpMZ,


	figLtL,
	figLtML,

	figUpL,
	figUpML,

	figDnL,
	figDnML,

	figRtL,
	figRtML,



	figMax=18,
	};
enum{
	gNo=0,
	gYes=1,
	gTwo,
	gThree,
	};
#endif